@startuml architecturalprofile

' skinparam Linetype ortho

frame "FCS Achitecture Structure" {

    object FederatedCubeSatSystem {
        +performanceRequirements
        +measurementSpecification
    }

    object SEGMENTS {
        +owner
    }
    object STAKEHOLDER {
        +id
    }
    object MISSION {
        +objective
        +goals
        +needs
    }

    FederatedCubeSatSystem ^-- SEGMENTS
    FederatedCubeSatSystem ^-- STAKEHOLDER
    FederatedCubeSatSystem ^-- MISSION

    object SPACESEGMENT {
        +orbit
        +#satellites
        +ROI
        +payload
        +engagement
    }
    object GROUNDSEGMENT {
        +location
    }
    object USERSEGMENT {
        +location
    }

    SEGMENTS ^-- SPACESEGMENT
    SEGMENTS ^-- GROUNDSEGMENT
    SEGMENTS ^-- USERSEGMENT
    
    frame "Constituent Systems" as cs {
        object SCD {
        +orbit: equatorial
        +#satellites: 2
        +ROI: Brazil
        +payload: Transponder DCS
        +engagement: 100%
    }
    object CBERS {
        +orbit: polar
        +#satellites: 1
        +ROI: Brazil
        +payload: Transponder DCS
        +engagement: 50%
    }
    object CONASAT {
        +orbit: TBD
        +#satellites: TBD
        +ROI: Brazil
        +payload: EDC
        +engagement: 100%
    }
    object CATARINA {
        +orbit: TBD
        +#satellites: 0
        +ROI: TBD
        +payload: EDC
        +engagement: TBD
    }

    SPACESEGMENT ^-- SCD
    SPACESEGMENT ^-- CBERS
    SPACESEGMENT ^-- CONASAT
    SPACESEGMENT ^-- CATARINA

    object GROUNDSTATION {
        +Id: string
        +MinimumElevationAngle: float
        +location: [float,float]
        +frequency: [string]
        +dataRate: [float]
    }
    object MISSIONCONTROL {
        +Id: string
        +location: [float,float]
        +groundStation: Id [string]
    }

    GROUNDSEGMENT ^-- GROUNDSTATION
    GROUNDSEGMENT ^-- MISSIONCONTROL

    object DCP {
        +frequency
        +datarate
        +dataStorage
    }

    USERSEGMENT ^-- DCP

    object SCD1 {
        ' +TLE1: 22490U 93009B   22062.68172372  .00000315  00000-0  36869-4 0  9991
        ' +TLE2: 22490  24.9688 147.4435 0043082 138.7341 352.8685 14.44649554534249
        +SMA: 7121 km
        +ECC: 0.0043226
        +INC: 24.9707 deg 
        +RAAN: 25.5298 deg
        +AOP: 0 deg
        +uplink: UHF, 400 b/s
        +downlink: S-Band
    }
    object SCD2 {
        ' +TLE1: 25504U 98060A   22063.14270493  .00000285  00000-0  29770-4 0  9996
        ' +TLE2: 25504  24.9969 358.6150 0017354 152.6186 331.7953 14.44165264233965
        +SMA: 7124 km
        +ECC: 0.0017301
        +INC: 24.9959 deg 
        +RAAN: 152.6186 deg
        +AOP: 0 deg
        +uplink: UHF, 400 b/s
        +downlink: S-Band
    }
    object CBERS4A {
        ' +TLE1: 40336U 14079A   22063.09024170  .00000021  00000-0  22404-4 0  9992
        ' +TLE2: 40336  98.4936 138.6168 0001817  76.9470 283.1933 14.35446246379298
        +SMA: 7151.6 km
        +ECC: 0.001817
        +INC: 98.4936 deg 
        +RAAN: 76.9470 deg
        +AOP: 0 deg
        +uplink: UHF, 400 b/s
        +downlink: S-Band
    }

    SCD ^-- SCD1
    SCD ^-- SCD2
    CBERS ^-- CBERS4A

    object EMMN {
        +Id: EMMN
        +MinimumElevationAngle: 7
        +location: [-5.83,324.79]
        +frequency: [VHF,UHF,S-band]  
        +datarate: TBD
    }
    object ETC {
        +Id: ETC
        +MinimumElevationAngle: 7
        +location: [-15.5,303.99]
        +frequency: [S-band]
        +datarate: TBD
    }
    object ETA {
        +Id: ETA
        +MinimumElevationAngle: 7
        +location: [-2.33,315.96]
        +frequency: S-band
        +datarate: TBD
    }

    GROUNDSTATION ^-- EMMN
    GROUNDSTATION ^-- ETC
    GROUNDSTATION ^-- ETA
    }

}

@enduml