@startuml architectural_include

' !include architecture_elements.plantuml

skinparam Linetype ortho

frame "FCS Achitecture Structure" {

    !include architecture_elements.plantuml

    FederatedCubeSatSystem ^-- SEGMENTS
    FederatedCubeSatSystem ^-- STAKEHOLDER
    FederatedCubeSatSystem ^-- MISSION

    SEGMENTS ^-- SPACESEGMENT
    SEGMENTS ^-- GROUNDSEGMENT
    SEGMENTS ^-- USERSEGMENT
    
    SPACESEGMENT ^-- SATELLITE
    
    GROUNDSEGMENT ^-- MISSIONCONTROL
    GROUNDSEGMENT ^-- GROUNDSTATION

}

@enduml