@startuml csrm

skinparam Linetype ortho

frame "CSRM" as csrm

frame "Architecture Structures" as arch
frame "Validation and Verification" as vandv
frame "Technical Measures" as measures
frame "Concerns and Requirements" as requirements

csrm +-- arch
csrm +-- vandv
csrm +-- measures
csrm +-- requirements

@enduml