@startuml modelprofile
allowmixing

package mission(golds,T) as ms {

    package demand(coverage,golds,T) {
        json coverageKPP {
            "ROI":["lat","lon","elevation"],
            "coverage":">70 %"
        }
    }
    package demand(revisitTime,golds,T) {
        json revisitKPP {
            "ROI":["lat","lon","elevation"],
            "revisitTIme":"< 1 hour"
        }
    }
    package demand(dataStorage,golds,T) {
        json storageKPP {
            "numberDCP":27,
            "dataPerDCP":"400 bps",
            "dataGenerated":"~ 889.89 MB/day"
        }
    }
    package demand(dataDownload,golds,T) {
        json downloadKPP {
            "storedData":"~ 1 GB/day",
            "FER":"10E-15"
        }
    }

}

@enduml