@startuml resourcesUser
allowmixing

''''''''''''''''' USER SEGMENT ''''''''''''''''
'''''''''''''''''''''''''''''''''''''''''''''''
package resource(user,T){
    package service(hidro,user,T){
        json hidroTPM {
            "ROI":"Brazil",
            "number of DCP":"TBC",
            "owner":"TBC",
            "DCP1 to N":["lat","lon","elevation"]
        }
    }
    package service(meteo,user,T){
        json meteoTPM {
            "ROI":"Brazil",
            "number of DCP":"TBC",
            "owner":"TBC",
            "DCP1 to N":["lat","lon","elevation"]
        }
    }
    package service(geo,user,T){
        json geoTPM {
            "ROI":"Brazil",
            "number of DCP":"TBC",
            "owner":"TBC",
            "DCP1 to N":["lat","lon","elevation"]
        }
    }
}

@enduml