@startuml resourcesModelling

frame "Resource and Services Profile" {
    
    
    frame "Resources Usage" {
        object Service {
            +Sum(b_i) = 1
        }
        object Resources {
            u_1*(b_1+b_2+..b_N) + ..
            u_2*(b_1+b_2+..b_N) + ..
            u_K*(b_1+b_2+..b_N) + ..
        }

        Service --> Resources : b_1
        Service --> Resources : b_2
        Service --> Resources : b_N
    }

    frame "Uses By Service" {
        object Service1
        object Service2
        object ServiceK
    
        object Resource {
            +sum(u_j) <= U
        }

        ServiceK --> Resource : u_K
        Service2 --> Resource : u_2
        Service1 --> Resource : u_1
        
    }
}

@enduml