@startuml vandvprofile

skinparam Linetype ortho

frame "Validation and Verification" {
    
    object Behaviour
    object ValidationActivity
    object VerificationActivity {
        +verificationMethod: kind
    }
    object Operation
    object Trace
    object Validation {
        +validate: Boolean
    }
    object Verify {
        ownedOperation = getVerifies
    }
    object Verification {
        +verified : boolean
    }

    Behaviour <-- ValidationActivity
    Behaviour <-- VerificationActivity
    Operation <-- VerificationActivity

    Trace ^-- Validation

    Verify ^-- Verification
}

@enduml